- theme/shippable/navbar.html
- theme/shippable/navbar_sub.html
Navbar change: click on section is equal to click on first section's article now instead of showing drop-down menu.
> fixed click navbar behaviour

- sources/config.md
This is being deprecated with the next prod push. Updating the docs to not describe the usage.
> Removing references to privileged and net

- mkdocs.yml
- sources/parallel_tests.md
Closes #119 
I added the page at the top of the how-to menu, you may want to change that.
> Adds parallel builds guide to docs

- theme/shippable/static/ash/css/custom.css
> Closes #152; Side bar too long

- sources/docker_registries.md
It looks like the markdown interpreter you're using on docs.shippable.com requires a newline before lists: see how the list currently renders: http://docs.shippable.com/docker_registries/
Switching to CommonMark would solve this kind of issues.
> Fix markdown list by adding a newline

- sources/docker_build.md
Replace invalid domain https://docs.dockerhub.com with valid
https://docs.docker.com.
> Fix broken link to official Docker documentation

- sources/ci_faq.md
https://github.com/Shippable/docsv2/issues/245
- Adds section explaining how to source rvm so a user can reference Ruby and rvm commands in their build.
- Also fixes some links.
Screenshot:
> Add section on how to use Ruby with another language

- sources/int_keys.md
I couldn't find any documentation earlier on how to use ssh/pem integrations. It got figured out (shippable/support#2646) but hopefully this can help others and save support some time.
> Added shippable.yml examples for key integrations

- sources/ci_configure.md
Fixes https://github.com/Shippable/docsv2/issues/381
We've added three new standard environment variables.  `COMMITTER`, `LAST_AUTHOR` & `COMMIT_MESSAGE`
I've checked the documentation on local to make sure the UI is not broken.
> Updated documentation to include the new env variables we've added. 

- sources/api.md
https://github.com/Shippable/docsv2/issues/427
Removes the /subscriptions/:id/activeMinions route from the API docs
revised section (it was before Delete a Subscription)
> Remove /subscriptions/:id/activeMinions route from API docs

- sources/pipelines/resources/cluster.md
Shippable/pm#7343
Documentation for the future `namespace` option, and some indentation changes to make everything line up.
> Add namespace option to cluster documentation.

- sources/pipelines/resources/loadBalancer.md
Shippable/pm#7349
Adds the future `role` option to the loadBalancer documentation and replaces some tabs with spaces so that the indentation will be as intended.
> Adds role option to loadBalancer documentation.

- sources/pipelines/resources/dockerOptions.md
https://github.com/Shippable/docsv2/issues/629
in ECS, in the "Top level docker options" section:
- we say `Service` but it should be `service`
- we say `Task Definition` but it should be `taskDefinition`
in "Top level docker options" for GKE:
- we say `Pod` but it should be `pod`
> dockerOptions docs spelling/caps

- mkdocs.yml
- sources/pipelines/jobs/deploy.md
- sources/pipelines/jobs/overview.md
- sources/pipelines/jobs/provision.md
- sources/pipelines/resources/loadBalancer.md
- sources/pipelines/resources/overview.md
https://github.com/Shippable/docsv2/issues/631
Adds provision job page:
Updates jobs overview to reference provisions (as well as jenkinsJobs):
Updates loadBalancer resource page to include info on GKE services:
Updates the loadBalancer reference in the resources overview to reflect GKE:
Updates the loadBalancer reference in the deploy jobs docs to reflect GKE:
> DO NOT MERGE: 5.1.2 deployment - Add provision jobs for GKE services

- sources/pipelines/jobs/runSh.md
- sources/tutorials/pipelines/runShUseIntegrations.md
https://github.com/Shippable/docsv2/issues/624
Adds the following env vars to the table:
- RESOURCE_ID
- RESOURCENAME_VERSION_VERSIONID
- RESOURCENAME_VERSION_FIELDNAME (these are the fields in the property bag; for dockerOptions, params, and replicas)
- RESOURCENAME_PARAMS_FIELDNAME for params-type resources only
> DO NOT MERGE - 5.1.2 deployment: adds resourceId, versionId, version propertyBag, and params runSh env vars  

- sources/pipelines/resources/gitRepo.md
#650 
Updates the `gitRepo` documentation to include `branches` and the options to enable and disable different types of webhooks.  And replaces some tabs with spaces.
> #650; updates gitRepo documentation.

- sources/tutorials/ci/integrations/codeCoverage/usingJacoco.md
https://github.com/Shippable/docsv2/issues/662
- Specifies the full path where Shippable looks for the jacoco.xml
- Removes redundant text
> Clarify path for jacoco.xml

- sources/pipelines/resources/dockerOptions.md
#634 
Adds `placementStrategy` to the ECS Docker options for services and fixes some formatting.
For after the AWS SDK is updated in Production.
> #634; [DO NOT MERGE] adds placementStrategy.

- sources/pipelines/jobs/runSh.md
https://github.com/Shippable/docsv2/issues/671
- Adds the gitRepo variables
- Removes the VERSION variables; the VERSIONID, VERSIONNAME and VERSIONNUMBER vars are now of the pattern <resourceName>_VERSIONID
- Removes all POINTER variables; <resourceName>_POINTER_SOURCENAME is now <resourceName>_SOURCENAME
- Removes all SEED variables, except <resourceName>_SEED_VERSIONNAME
Revised section: 
New section:
> DO NOT MERGE - 5.1.5 release: Add gitRepo variables and remove VERSION and most POINTER and SEED vars

- sources/pipelines/jobs/runCLI.md
- sources/pipelines/resources/cliConfig.md
#689 
Adds the rest of the supported integration types to the runCLI documentation.  This is for the next release.
> #689; adds more integration types to runCLI documentation.

- sources/pipelines/jobs/runCLI.md
- sources/pipelines/jobs/runSh.md
#700 
For 5.2.3, this adds even more Pipelines environment variables and a note about Terraform and Packer.
> #700; adds more pipelines environment variables.

- sources/tutorials/pipelines/connectingCiPipelines.md
- sources/tutorials/pipelines/samplePipeline.md
#707 
updates the tutorial, and removes the instructions for using eventTriggers from both spots.
> modify docs for runCI support

- sources/ci/languages/python.md
https://github.com/Shippable/docsv2/issues/711
Changes `2.7.6` to `2.7` to match what virtualenv expects (using 2.7.6 in a yml will give an error); this is also how other versions are specified.
> Change 2.7.6. to 2.7 to be consistent with virtualenv and other versions

- sources/pipelines/jobs/runSh.md
#713 
For the next release.  Adds two new environment variables to the documentation for runSh.
> #713; adds SSH and HTTPS URLs to runSh documentation.

- sources/pipelines/jobs/manifest.md
https://github.com/Shippable/docsv2/issues/736
The link it is currently pointing to was removed in this [PR](https://github.com/Shippable/docsv2/pull/552)
> removing the usingCombinationManifests tutorial link

- sources/legacyFiles/ci_projects.md
- sources/navigatingUI/projects/settings.md
https://github.com/Shippable/pm/issues/8000
I am not able to find out where `sources/legacyFiles/ci_projects.md` renders in UI.
> updates docs to include new scm providers for tags
