Shippable/docsv2

README.md
sources/yml.md
theme/shippable/article.html
theme/shippable/static/ash/css/custom.css
theme/shippable/static/ash/js/custom.js

- hiding sidebar on extra small and small displays we can have sticky thing with no problem
- now yml.md looks like a good candidate to split under "Configuration" section (especially with sticky tocbar)

sticky tocbar, fixed yaml.md

---

theme/shippable/static/ash/css/custom.css

No browser testing but it looks working somehow..

fixed mobile menus

---

theme/shippable/article.html
theme/shippable/static/ash/js/custom.js

going sticky only if it is possible

fixed sticky for big tocs

---

theme/shippable/base.html

a try to fix the Manisha's favicon issue

update favicon, remove little necko favicons for apple

---

sources/start.md

yml overview is a better reference page

Changed yml reference link to yml overview

---

sources/languages/images.md

and changed it to refer to project settings.
IMPORTANT: PLEASE MERGE the 8 PRS in ShippableSamples for the samples linked to this page.

 removed build image reference in the yml

---

theme/shippable/base.html
theme/shippable/header.html
theme/shippable/static/ash/css/custom.css

https://github.com/Shippable/pm/issues/3862

Fix main nav missing update.

---

theme/shippable/footer.html
theme/shippable/static/ash/css/custom.css

https://github.com/Shippable/pm/issues/3873
#72

Make docs footer same as www

---

theme/shippable/base.html
theme/shippable/static/ash/css/custom.css

https://github.com/Shippable/pm/issues/3895
#74

Fix install of Proxima Nova font.

---

theme/shippable/navbar.html
theme/shippable/static/ash/css/custom.css

https://github.com/Shippable/pm/issues/3890
#77

Make sub-nav dropdowns accordion in moble size

---

mkdocs.yml
sources/build_badge.md

https://github.com/Shippable/docsv2/issues/99

adding a how-to section for badge

---

sources/faq.md

closes https://github.com/Shippable/docsv2/issues/115

add yml validation faq

---

sources/integrations.md

* replaced reference to Docker Hub with Quay.io
* added clarification on where to look to find Account Settings

edit to integrations page

---

sources/lighthouse.md
theme/shippable/article.html
theme/shippable/scripts_bottom.html
theme/shippable/static/ash/css/custom.css
theme/shippable/static/ash/js/accordion.js

https://github.com/Shippable/pm/issues/4156
#122

Implement accordion for side nav (#122).

---

theme/shippable/navbar.html
theme/shippable/navbar_sub.html

fix link issues on nav bar

---

theme/shippable/navbar.html
theme/shippable/navbar_sub.html
theme/shippable/static/ash/css/custom.css

https://github.com/Shippable/pm/issues/4503
Fixes #138

Fix how to menu being too long

---

sources/docker_registries.md
sources/integrations.md

Made small changes to the links and Instructions
Closes #150

Closes #150; small changes to GCR

---

sources/api.md

closes https://github.com/Shippable/docs/issues/169

update api docs for searchBuilds

---

sources/languages.md

fixes https://github.com/Shippable/docsv2/issues/155

updates clojure docs with references to test2junit

---

sources/ci_overview.md

Fixes https://github.com/Shippable/docsv2/issues/158

Update description for PR Builds and Queued Builds on CI overview page

---

sources/ci_configure.md

updated values for hub integration types 'ecr' and 'quay.io' in two places.

correct hub integration types

---

sources/ci_configure.md

Fixes https://github.com/Shippable/docsv2/issues/181

updates ci_configure with note for hub integrations

---

theme/shippable/scripts_bottom.html

https://github.com/Shippable/www/issues/4318

Add Google remarketing code to all site pages (#4318).

---

sources/ci_configure.md

Fixes https://github.com/Shippable/docsv2/issues/194

adds description for  env var

---

sources/ci_configure.md

https://github.com/Shippable/support/issues/2275

Adds SHIPPABLE_PYTHON_VERSION to ci_config section

---

sources/ci_configure.md

@manishas or @avinci  : please review it.

updated path for cache_dir_list

---

theme/shippable/scripts_bottom.html

https://github.com/Shippable/docsv2/issues/224

Move redirect script above original MKdocs search scripts.

---

sources/ci_configure.md
sources/gs_supported.md
sources/int_notifications.md
sources/int_overview.md
sources/lighthouse.md

added docs for hipchat integration 

---

sources/ci_configure.md

references https://github.com/Shippable/pm/issues/5794
fixes https://github.com/Shippable/docsv2/issues/248

Updated the docs with the new env variable IS_FORK

---

sources/api.md
sources/ci_configure.md

Fixes https://github.com/Shippable/docsv2/issues/252

adds docs about inject global env variables

---

sources/lighthouse.md

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shippable/docsv2/259)

Fix typo :)

---

sources/ci_languages.md

https://github.com/Shippable/docsv2/issues/260

update for PHP7

---

sources/ci_languages.md

changes php7 image name from u14php7pls to u14phpall

updates php7 image

---

sources/api.md
sources/ci_configure.md
sources/ci_languages.md
sources/gs_supported.md

adds documentation for c language 

---

sources/ci_configure.md

Fix typo (#270).

---

sources/ci_configure.md

Fixes https://github.com/Shippable/docsv2/issues/279

add docs for overriding service startup command

---

sources/int_container_services.md
sources/pipelines_configure.md

- https://github.com/Shippable/pm/issues/5863

adding documentation for cross account IAM authentication

---

sources/ci_configure.md

https://github.com/Shippable/docsv2/issues/279
Fixing
Area highlighted more than required

correct docs for custom startup of services

---

.gitignore
sources/int_container_services.md

- https://github.com/Shippable/docsv2/issues/286

286 update iam docs

---

sources/gs_supported.md
sources/int_docker_registries.md

update docs for Docker Trusted Registry 

---

sources/ci_faq.md
sources/int_scm.md

https://github.com/Shippable/docsv2/issues/304

updated the need to enable private repo in account settings

---

sources/int_docker_registries.md

https://github.com/Shippable/docsv2/issues/315

update quay.io docs

---

sources/ci_configure.md
sources/ci_overview.md

https://github.com/Shippable/docsv2/issues/310

[do not merge] Updated docs with usage details of tag and release variables

---

sources/pipelines_configure.md

update docs for Infra projects 

---

sources/int_docker_registries.md

For using the Docker Private Registry while fetching the tags.
https://github.com/Shippable/docsv2/issues/333

Adds note about using Docker API v2

---

sources/ci_configure.md

Fixes https://github.com/Shippable/docsv2/issues/344

adds Event Triggers section to ci_configure

---

sources/ci_docker.md
sources/ci_faq.md
sources/ci_subscriptions.md

from https://github.com/Shippable/docsv2/issues/332

add machine images documentation

---

sources/int_container_services.md

The policy was not validated by aws.

valid amazon policy

---

sources/gs_deploy_sample.md
sources/pipelines_configure.md
sources/pipelines_faq.md
sources/pipelines_overview.md
sources/pipelines_subscriptions.md

Covers the 5 documents under Pipelines.

Added separators between sections and added cross-links

---

sources/api.md
sources/ci_configure.md
sources/ci_docker.md
sources/ci_faq.md
sources/ci_languages.md
sources/ci_overview.md
sources/gs_ci_sample.md
sources/gs_deploy_sample.md
sources/gs_plans.md
sources/gs_supported.md
sources/index.md
sources/int_overview.md
sources/lighthouse.md
sources/pipelines_configure.md
sources/pipelines_faq.md
sources/pipelines_overview.md
theme/shippable/static/ash/css/custom.css

Closes #369 
Closes https://github.com/Shippable/mktg/issues/1431

Add CTAs to certain pages (#370).

---

sources/gs_supported.md
sources/ht_using_bitbucket_server.md
sources/index.md
sources/int_overview.md
sources/int_scm.md

https://github.com/Shippable/docsv2/issues/325

Add Bitbucket Server docs

---

theme/shippable/header.html
theme/shippable/static/ash/css/custom.css

Make sure nav bar is the same as mktg site (#386)

---

sources/ci_builds.md
sources/ci_configure.md
sources/ci_projects.md

https://github.com/Shippable/docsv2/issues/405

updated info about timeouts for free and paid accounts

---

sources/ci_projects.md
sources/ci_subscriptions.md

Closes https://github.com/Shippable/docsv2/issues/478

Encrypt moved from projects to subscriptions

---

theme/shippable/article.html
theme/shippable/base.html
theme/shippable/navbar_sub.html
theme/shippable/scripts_bottom.html
theme/shippable/static/ash/css/fleming.css
theme/shippable/static/ash/js/accordion.js

Closes https://github.com/Shippable/pm/issues/6471

Style page body with left accordion nav + change to faster loading font + add right side menu

---

theme/shippable/footer.html
theme/shippable/header.html

Closes https://github.com/Shippable/pm/issues/6637
Also fixes footer links.

Fix links in top navbar are all broken (PM#6637).

---

theme/shippable/static/ash/css/fleming.css

Closes https://github.com/Shippable/pm/issues/6592

Fix left-hand nav misaligned (PM#6592).

---

sources/pipelines/jobs/release.md

should close https://github.com/Shippable/pm/issues/6865

corrects description of bump in release

---

theme/shippable/footer.html
theme/shippable/header.html

Part of https://github.com/Shippable/pm/issues/6908

Fix missing resources link and wrong image sources in header/footer.

---

sources/ci/shippableyml.md

There is no page for Kestrel BTW

Fix links to services pages

---

sources/api/job.md

https://github.com/Shippable/docsv2/issues/596

updating the job consoles download route

---

sources/pipelines/resources/dockerOptions.md

update dockerOptions to include latest supported fields

---

sources/pipelines/jobs/deploy.md
sources/pipelines/jobs/manifest.md

https://github.com/Shippable/docsv2/issues/603

adding file resource reference in manifest and deploy jobs

---

sources/pipelines/resources/dockerOptions.md

https://github.com/Shippable/docsv2/issues/607

adds missing docker cloud reference link

---

theme/shippable/article.html

https://github.com/Shippable/docsv2/issues/613

Corrects the link for edit in github

---

sources/faq.md

Fix typo for nodejs link

---

theme/shippable/footer.html

#622 
Updates 2016 to 2017 at the bottom of all pages.

#622; updates copyright in footer.

---

sources/pipelines/jobs/runSh.md
sources/tutorials/pipelines/runShUseIntegrations.md

https://github.com/Shippable/docsv2/issues/619
- Adds runSh environment variables section:
- Revises runSh environment variables tutorial:

DO NOT MERGE - 5.1.1 deployment: Add runSh env vars section; revise runSh env vars tutorial

---

sources/tutorials/pipelines/extractVersionInformation.md

https://github.com/Shippable/docsv2/issues/644

updates the version.json and adds the version.json for file resource

---

sources/pipelines/resources/dockerOptions.md

Adds container and top level docker options details

---

sources/navigatingUI/projects/settings.md
sources/pipelines/jobs/runSh.md

https://github.com/Shippable/pm/issues/7675

removes the extra TASK section in the example yml

---

sources/pipelines/jobs/overview.md
sources/pipelines/jobs/runSh.md

https://github.com/Shippable/pm/issues/7703

added the always task section

---

sources/api/project.md

https://github.com/Shippable/docsv2/issues/680
- Updates the results of GET /projects, GET/projects/:projectId, and GET /projects/:projectId/branchRunStatus

Update returned objects for project routes

---

mkdocs.yml
sources/pipelines/resources/cliConfig.md
sources/pipelines/resources/file.md
sources/pipelines/resources/overview.md

#686 
This adds the cliConfig resource page, and a link to the file page from the resources overview, for the next release.

#686; 5.2.1 cliConfig resource.

---

sources/pipelines/jobs/runSh.md

#691 
For 5.2.3.  This adds the newly-added environment variables to the documentation.

#691; adds more environment variables to runSh documentation.

---

sources/faq.md

https://github.com/Shippable/pm/issues/7735

Do not merge until 5.2.3 release. info on genexec

---

sources/ci/languages/java.md
sources/tutorials/ci/code-coverage-jacoco.md

To be merged once all subs are using the S3 workflow.
#692

[defer merge] Deprecate advancedReporting flag

---

sources/pipelines/jobs/runSh.md

add new envs for gitRepo and ssh/pem keys

---

sources/pipelines/jobs/provision.md

https://github.com/Shippable/docsv2/issues/717

adds the kubernetes services

---

sources/pipelines/resources/dockerOptions.md

https://github.com/Shippable/docsv2/issues/719

updates the provider specific docker options for kubernetes

---

sources/ci/advancedOptions/environmentVariables.md

https://github.com/Shippable/docsv2/issues/723

Adds yml dictionary format

---

sources/ci/advancedOptions/machineImages.md
sources/navigatingUI/subscriptions/settings.md

Fixes #725 
Merge only after v5.3.1 goes live.

Update docs for new system machine images

---

theme/shippable/scripts_bottom.html

https://github.com/Shippable/docsv2/issues/738

add search.js only in Search page

---

sources/ci/languages/clojure.md
sources/ci/languages/go.md
sources/ci/languages/java.md
sources/ci/languages/node.md
sources/ci/languages/objc.md
sources/ci/languages/php.md
sources/ci/languages/python.md
sources/ci/languages/ruby.md
sources/ci/languages/scala.md

Update language pages to describe new images

---

sources/pipelines/resources/params.md

https://github.com/Shippable/docsv2/issues/744
- Adds descriptions of how params can be used with runSh and runCLI jobs
- Includes a link to the list of params env vars that are added to runSh and runCLI jobs

Include info on params as inputs to unmanaged jobs

---

shippable.yml

Publish to rcdocs.shippable.com

---

sources/ci/advancedOptions/sshKeys.md

https://github.com/Shippable/docsv2/issues/747

fix alignments

---

sources/integrations/containerServices/ecs.md

Fixed policy statement
Fixed AWS credentials link

Fix for PM issues 8202, 8206

---

sources/ci/services/mySQL.md

Update mysql docs to reflect new GRANT behaviour

---

sources/tutorials/ci/deploy-heroku.md

https://github.com/Shippable/docsv2/issues/762
me and @Varsha-Arun Verified this on prod:
**withouttoolbelt**:
yml link: https://github.com/shiptest-rc-me/sample_node_heroku/blob/withouttoolbelt/shippable.yml
build link: https://app.shippable.com/github/shiptest-rc-me/sample_node_heroku/runs/2/1/console
**withtoolbelt**:
yml link: https://github.com/shiptest-rc-me/sample_node_heroku/blob/withtoolbelt/shippable.yml
build link: https://app.shippable.com/github/shiptest-rc-me/sample_node_heroku/runs/4/1/console

Update Shippable Heroku Documentation

---

sources/ci/machine-images/v5-4-1.md

https://github.com/Shippable/docsv2/issues/769

Replace ??? in ci/machine-images/v5-4-1/ with 5.4.1

---

sources/navigatingUI/subscriptions/settings.md

adding docs for new event trigger toggle

---

sources/pipelines/gettingStarted.md

fixes https://github.com/Shippable/docsv2/issues/774

Adds documentation about grid view

---

sources/ci/advancedOptions/testCoverage.md
sources/legacyFiles/ci_configure.md

https://github.com/Shippable/heap/issues/725
Its already been done [here](https://github.com/Shippable/micro/blob/master/nod/jobRequest/_common/_templates/providers/_github.sh#L38)

updates docs to not ask users to create testresults and codecoverage directories

---

sources/pipelines/resources/dockerOptions.md

https://github.com/Shippable/pm/issues/8322

adds labels in kubernetes deployment spec level dockerOptions

---

sources/pipelines/resources/notification.md

https://github.com/Shippable/docsv2/issues/778

adds docs to support irc for buildJobs

---

sources/integrations/notifications/email.md

https://github.com/Shippable/docsv2/issues/784
This should also be added here (Integrations/notifications/email)

document sendConsoleLogs and sendCoverageReports

---

sources/integrations/notifications/email.md

https://github.com/Shippable/pm/issues/8302

document unsupported files

---

sources/pipelines/resources/gitRepo.md

https://github.com/Shippable/docsv2/issues/787

add tags.only and tags.except field for gitRepo resource

---

sources/ci/advancedOptions/environmentVariables.md
sources/legacyFiles/ci_configure.md
sources/pipelines/jobs/runSh.md

Fixes https://github.com/Shippable/docsv2/issues/805

Update docs for new env variable available while running a CI/runsh job

---

mkdocs.yml
sources/ci/machine-images/v5-4-1.md
sources/ci/machine-images/v5-5-1.md

https://github.com/Shippable/docsv2/issues/808

Add v5.5.1 system machine images documentation

---

sources/pipelines/resources/dockerOptions.md

update portmapping description

---

sources/pipelines/resources/dockerOptions.md

Reverts Shippable/docsv2#780
https://github.com/Shippable/pm/issues/8322

Revert "adds labels in kubernetes deployment spec level dockerOptions"

---

sources/pipelines/resources/dockerOptions.md

add docs for kube live/ready support and other options
